language: perl
perl: 5.20

before_install:
  - sudo apt-get install libluajit-5.1-dev libluajit-5.1.2 libyaml-0-2 libyaml-dev

install:
  - mkdir ./vendor && cd ./vendor

  - wget http://nginx.org/download/nginx-1.6.0.tar.gz && tar -xf nginx-1.6.0.tar.gz
  - wget https://github.com/openresty/lua-nginx-module/archive/v0.9.13rc1.tar.gz -O lua-nginx-module-0.9.13rc1.tar.gz && tar -xf lua-nginx-module-0.9.13rc1.tar.gz
  - wget https://github.com/simpl/ngx_devel_kit/archive/v0.2.19.tar.gz -O ngx-devel-kit-0.2.19.tar.gz && tar -xf ngx-devel-kit-0.2.19.tar.gz

  - cd ./nginx-1.6.0
  - export LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
  - export LUAJIT_INC=/usr/include/luajit-2.0/
  - ./configure --add-module=../ngx_devel_kit-0.2.19 --add-module=../lua-nginx-module-0.9.13rc1 --add-module=../../
  - sudo make install
  - export PATH=$PATH:/usr/local/nginx/sbin

  - cpanm -v --notest Test::Nginx

script: cd ${TRAVIS_BUILD_DIR} && prove
