language: perl
perl: 5.20

env:
  - VER_NGINX=1.6.2
  - VER_NGINX=1.7.6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq libluajit-5.1-dev libluajit-5.1-2
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
  - mkdir ./vendor && cd ./vendor

  - wget "http://nginx.org/download/nginx-${VER_NGINX}.tar.gz" && tar -xf "nginx-${VER_NGINX}.tar.gz"

  - wget https://github.com/openresty/lua-nginx-module/archive/v0.9.13rc1.tar.gz -O lua-nginx-module-0.9.13rc1.tar.gz && tar -xf lua-nginx-module-0.9.13rc1.tar.gz

  - cd "./nginx-${VER_NGINX}"
  - export LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
  - export LUAJIT_INC=/usr/include/luajit-2.0/
  - ./configure --add-module=../lua-nginx-module-0.9.13rc1 --add-module=../../
  - sudo make install
  - export PATH=$PATH:/usr/local/nginx/sbin

  - cpanm -v --notest Test::Nginx

script: cd ${TRAVIS_BUILD_DIR} && prove
